### ISSUE TITLE
Error: Failed applying patch luarocks_vs_compiler.patch

### ISSUE THREAD

**Issue by Excrulon** [brunoos/luasec#82]
I'm trying to use this with luarocks and I'm getting this error.

```
luarocks install luasec OPENSSL_DIR=C:\Build-OpenSSL-VC-32
Installing http://luarocks.org/repositories/rocks/luasec-0.6-1.rockspec...
Cloning into 'luasec'...
remote: Counting objects: 872, done.
remote: Total 872 (delta 0), reused 0 (delta 0), pack-reused 872
Receiving objects: 100% (872/872), 689.99 KiB | 0 bytes/s, done.
Resolving deltas: 100% (523/523), done.
Checking connectivity... done.
Applying patch luarocks_vs_compiler.patch...
source/target file does not exist
--- src/ssl.c.orig

+++ C:\Users\Username\AppData\Local\Temp\luarocks_luasec-0.6-1-6833\luasec/src/ssl.c


Error: Failed applying patch luarocks_vs_compiler.patch
```

I see that the .rockspec file has this in it but I'm not sure what the issue is, exactly.

```
         patches = {
            ["luarocks_vs_compiler.patch"] = [[
--- a/src/ssl.c.orig
+++ b/src/ssl.c
@@ -844,3 +844,8 @@ LSEC_API int luaopen_ssl_core(lua_State *L)

   return 1;
 }
+
+#if defined(_MSC_VER)
+/* Empty implementation to allow building with LuaRocks and MS compilers */
+LSEC_API int luaopen_ssl(lua_State *L) { return 0; }
+#endif
]]
         }
```

Any ideas?

**Comment by brunoos** [comment]
It worked fine for me using Lua 5.1, Windows 7, VC11, OpenSSL 1.0.2j.

**Comment by sle118** [comment]
Trying to get this to work on Lua 5.1, Windows 7 64 bits, VC12, OpenSSL 1.0.2j (32 bits) and getting the same error as @Excrulon.

**Comment by thegrb93** [comment]
I've just got this too. Using OpenSSL-Win32 and Lua 5.1 for windows.

**Comment by thegrb93** [comment]
Version 0.6-1 also gives this error.

**Comment by thegrb93** [comment]
Version 0.5.1-1 gives
```
luarocks install luasec 0.5.1-1 OPENSSL_DIR="C:\Program Files (x86)\OpenSSL-Win32"
Installing http://luarocks.org/repositories/rocks/luasec-0.5.1-1.rockspec...
Cloning into 'luasec'...
remote: Counting objects: 877, done.
remote: Total 877 (delta 0), reused 0 (delta 0), pack-reused 877
Receiving objects: 100% (877/877), 695.15 KiB | 840.00 KiB/s, done.
Resolving deltas: 100% (526/526), done.
Checking connectivity... done.
cl /MD /O2 -c -Fosrc/x509.obj -IC:/Program Files (x86)/Lua/5.1/include src/x509.c -DWIN32 -DNDEBUG -D_WINDOWS -D_USRDLL -DLUASEC_EXPORTS -DBUFFER_DEBUG -DLUASEC_API=__declspec(dllexport) -Isrc/ -Isrc/luasocket
Microsoft (R) C/C++ Optimizing Compiler Version 18.00.21005.1 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

x509.c
src/x509.c(22) : fatal error C1083: Cannot open include file: 'openssl/ssl.h': No such file or directory

Error: Build error: Failed compiling object src/x509.obj
```

**Comment by thegrb93** [comment]
Apparently it's still having problems finding openssl even with OPENSSL_DIR set?

**Comment by brunoos** [comment]
Patch section was removed from rockspec.
